"""empty message

Revision ID: aa4ec65ebe06
Revises: c1f1e55be76b
Create Date: 2020-03-10 13:02:50.248396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa4ec65ebe06'
down_revision = 'c1f1e55be76b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_info_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('sex', sa.String(length=128), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('wetght', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['name'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personal_info_table')
    # ### end Alembic commands ###
